Producto/urls.py
from django.urls import path
from . import views

app_name = 'Producto'

urlpatterns = [
    path('listar_productos/', views.listar_productos, name='listar_productos'),
    path('agregar_producto/', views.agregar_producto, name='agregar_producto'),
    path('producto/editar/<int:producto_id>/', views.editar_producto, name='editar_producto'),
    path('producto/eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    #path('agregar_componentes/<int:producto_id>/', views.agregar_componentes, name='agregar_componentes'),
    path('get_productos/', views.get_productos, name='get_productos'),
    path('productos_fabricacion/', views.listar_productos_fabricacion, name='listar_productos_fabricacion'),
    path('producto/<int:producto_id>/aumentar/', views.aumentar_stock, name='aumentar_stock'),
    path('producto/<int:producto_id>/detalle/', views.ver_detalle_producto, name='ver_detalle_producto'),
    #path('productos/seleccionar_principal/', views.seleccionar_producto_principal, name='seleccionar_producto_principal'),
    #path('producto/<int:producto_id>/agregar_componentes/', views.agregar_componentes, name='agregar_componentes'),
    path('producto/<int:producto_id>/editar-componentes/', views.editar_componentes_producto, name='editar_componentes_producto'),
    # Añadir más URLs aquí
]

Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Aplicacion.urls', namespace='Aplicacion')),
    path('', include('Usuarios.urls', namespace='Usuarios')),
    path('', include('Producto.urls', namespace='Producto')),
    path('admin/', admin.site.urls),
]

Producto/models.py
from django.db import models

class Producto(models.Model):
    codigo = models.CharField(max_length=50, unique=True)
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField(blank=True, null=True)
    precio_compra = models.DecimalField(max_digits=10, decimal_places=2)
    precio_venta = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=0)
    tiene_descuento = models.BooleanField(default=False)
    para_fabricacion = models.BooleanField(default=False)
    componentes = models.ManyToManyField('self', through='ComponenteProducto', symmetrical=False, blank=True)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre

class ComponenteProducto(models.Model):
    producto_principal = models.ForeignKey(
        Producto,
        related_name='componentes_principal',  # Cambiado para ser único
        on_delete=models.CASCADE
    )
    producto_componente = models.ForeignKey(
        Producto,
        related_name='componentes_asociados',  # Cambiado para ser único, si es necesario
        on_delete=models.CASCADE
    )
    cantidad = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.producto_componente.nombre} en {self.producto_principal.nombre}"
    @property
    def costo_total(self):
        return self.cantidad * self.producto_componente.precio_compra



class Transaccion(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    fecha_registro = models.DateTimeField(auto_now_add=True)
    # Puedes incluir más campos relevantes aquí, como usuario que realizó la transacción, etc.

    def __str__(self):
        return f"Transacción de {self.cantidad} para {self.producto.nombre} el {self.fecha_registro}"

Producto/forms.py
from django import forms
from .models import Producto, ComponenteProducto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['codigo', 'nombre', 'descripcion', 'precio_compra', 'precio_venta', 'stock', 'tiene_descuento' ,'para_fabricacion']


class ComponenteProductoForm(forms.ModelForm):
    class Meta:
        model = ComponenteProducto
        fields = ['producto_componente', 'cantidad']

    def __init__(self, *args, **kwargs):
        super(ComponenteProductoForm, self).__init__(*args, **kwargs)
        self.fields['producto_componente'].queryset = Producto.objects.filter(activo=True)

class ProductoPrincipalForm(forms.Form):
    producto_principal = forms.ModelChoiceField(
        queryset=Producto.objects.filter(activo=True),  # Aquí se filtra por productos activos
        label="Seleccionar Producto Principal",
        empty_label="Seleccione un Producto",
        widget=forms.Select(attrs={'class': 'form-control'})
    )

Producto/views.py
from pyexpat.errors import messages
from django.shortcuts import render, redirect,  get_object_or_404
from django.db import transaction
from .models import Producto, ComponenteProducto, Transaccion
from .forms import ProductoForm, ComponenteProductoForm, ProductoPrincipalForm
from django.http import JsonResponse
from django.forms import modelformset_factory, inlineformset_factory

def listar_productos(request):
    producto = Producto.objects.filter(activo=True)  # Assuming 'activo' is a BooleanField in your model
    return render(request, 'Producto/listar_productos.html', {'productos': producto})


def get_productos(request):
    producto = Producto.objects.filter(activo=True).values('nombre', 'precio_compra')
    return JsonResponse(list(producto), safe=False)
 


#para ver la lista de productos marcados como fabricacion
def listar_productos_fabricacion(request):
    productos_para_fabricacion = Producto.objects.filter(activo=True, para_fabricacion=True)
    return render(request, 'Producto/lista_productos_prod.html', {'productos': productos_para_fabricacion})


def agregar_producto(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Producto:listar_productos')
        else:
            # Si el formulario de producto no es válido, muestra los errores en la misma página.
            return render(request, 'Producto/agregar_producto.html', {'form': form})
    else:
        form = ProductoForm()
        return render(request, 'Producto/agregar_producto.html', {'form': form})


def editar_producto(request, producto_id):
    # Obtén el producto que quieres editar o manda un error 404 si no existe
    producto = get_object_or_404(Producto, id=producto_id)

    if request.method == 'POST':
        # Crea una instancia del formulario y rellénalo con los datos de la petición (binding):
        form = ProductoForm(request.POST, instance=producto)
        if form.is_valid():
            # Guarda el producto editado en la base de datos
            form.save()
            # Redirige a la lista de productos o a la vista de detalles del producto
            return redirect('Producto:listar_productos')
    else:
        # Crea el formulario con los datos del producto que se va a editar
        form = ProductoForm(instance=producto)

    # Renderiza la plantilla con el formulario
    return render(request, 'Producto/editar_producto.html', {'form': form, 'producto': producto})


def eliminar_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    producto.activo = False  # Suponiendo que tienes un campo "activo" en el modelo Producto
    producto.save()
    return redirect('Producto:listar_productos')


@transaction.atomic  # Asegura que las operaciones sean atómicas
def aumentar_stock(request, producto_id):
    producto_principal = get_object_or_404(Producto, id=producto_id)
    if producto_principal.para_fabricacion:  # Asegúrate de que este campo exista en tu modelo Producto
        if request.method == 'POST':
            cantidad_a_fabricar = int(request.POST.get('cantidad', 0))  # Asegúrate de validar este valor correctamente.
            
            # Inicia una lista para controlar si todos los componentes tienen stock suficiente
            componentes_insuficientes = []

            # Verifica si hay suficientes componentes para la cantidad a fabricar
            for componente in ComponenteProducto.objects.filter(producto_principal=producto_principal):
                if componente.cantidad * cantidad_a_fabricar > componente.producto_componente.stock:
                    componentes_insuficientes.append(componente.producto_componente.nombre)
            
            if not componentes_insuficientes:
                # Actualiza el stock del producto principal
                producto_principal.stock += cantidad_a_fabricar
                producto_principal.save()

                # Disminuir la cantidad de materia prima
                for componente in ComponenteProducto.objects.filter(producto_principal=producto_principal):
                    producto_componente = componente.producto_componente
                    producto_componente.stock -= componente.cantidad * cantidad_a_fabricar
                    producto_componente.save()

                # Registra la transacción
                Transaccion.objects.create(
                    producto=producto_principal,
                    cantidad=cantidad_a_fabricar,
                    # La fecha de registro se añade automáticamente con auto_now_add=True en el modelo
                )

                return redirect('Producto:listar_productos_fabricacion')
            else:
                # Manejar la falta de componentes mostrando un mensaje al usuario
                # Podrías añadir un mensaje al contexto para informar qué componentes no tienen stock suficiente
                return render(request, 'Producto/aumentar_stock.html', {
                    'producto': producto_principal,
                    'error': f"No hay suficiente stock para los componentes: {', '.join(componentes_insuficientes)}."
                })

        return render(request, 'Producto/aumentar_stock.html', {'producto': producto_principal})
    else:
        # Si el producto no es fabricable, redireccionar o mostrar un mensaje de error
        return redirect('Producto:listar_productos')
    
    
def ver_detalle_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    componentes = ComponenteProducto.objects.filter(producto_principal=producto).select_related('producto_componente')
    
    # Crear una lista de componentes con su nombre y la cantidad necesaria para la fabricación del producto
    lista_componentes = [
        {
            'nombre': componente.producto_componente.nombre,
            'cantidad_necesaria': componente.cantidad,
            'stock_actual': componente.producto_componente.stock
        }
        for componente in componentes
    ]

    context = {
        'producto': producto,
        'componentes': lista_componentes
    }

    return render(request, 'Producto/ver_detalle_producto.html', context)



from django.db.models import F, Sum

def editar_componentes_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    ComponenteProductoFormSet = inlineformset_factory(
        Producto, 
        ComponenteProducto, 
        form=ComponenteProductoForm, 
        fields=('producto_componente', 'cantidad'), 
        extra=1,
        can_delete=True,
        fk_name='producto_principal'
    )
    
    if request.method == 'POST':
        formset = ComponenteProductoFormSet(request.POST, instance=producto, prefix='componentes')
        if formset.is_valid():
            formset.save()

            # Calcular el costo total de producción después de guardar el formset
            costo_total_produccion = producto.componentes_principal.annotate(
                total_cost=F('cantidad') * F('producto_componente__precio_compra')
            ).aggregate(Sum('total_cost'))['total_cost__sum'] or 0

            # Establecer el costo total de producción como el nuevo precio de compra
            producto.precio_compra = costo_total_produccion
            producto.save()

            return redirect('Producto:listar_productos_fabricacion')
    else:
        formset = ComponenteProductoFormSet(instance=producto, prefix='componentes')

        # Calcular el costo total de producción para mostrarlo en el formulario, pero no guardarlo aún
        costo_total_produccion = producto.componentes_principal.annotate(
            total_cost=F('cantidad') * F('producto_componente__precio_compra')
        ).aggregate(Sum('total_cost'))['total_cost__sum'] or 0

    return render(request, 'Producto/editar_componentes_producto.html', {
        'formset': formset,
        'producto': producto,
        'costo_total_produccion': costo_total_produccion,
    })

Producto/templates/Producto/agregar_producto.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Agregar Producto</h2>
    <br>
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a href="{% url 'Producto:listar_productos' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

Producto/templates/Producto/aumentar_stock.html
{% extends "base.html" %}

{% block content %}
<h1>Aumentar Stock de {{ producto.nombre }}</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="cantidad">Cantidad a fabricar:</label>
        <input type="number" id="cantidad" name="cantidad" min="1" class="form-control" required>
    </div>
    <button type="submit" class="btn btn-primary">Aumentar Stock</button>
</form>

{% if error %}
<div class="alert alert-danger" role="alert">
    {{ error }}
</div>
{% endif %}

<a href="{% url 'Producto:listar_productos_fabricacion' %}">Volver a la lista de productos</a>

{% endblock %}

Producto/templates/Producto/editar_componentes_producto.html
{% extends "base.html" %}
{% load my_filters %}

{% block content %}
<h2>Editar Componentes para: {{ producto.nombre }}</h2>

<form method="post" class="my-form">
    {% csrf_token %}
    {{ formset.management_form }}
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Componente</th>
                <th>Cantidad</th>
                <th>Precio Compra</th>
                <th>Costo Total</th>
                <th>Eliminar</th>
            </tr>
        </thead>
        <tbody>
            {% for form in formset %}
                <tr class="form-group">
                    <td>{{ form.id }}</td>
                    <td>
                        <label>{{ form.producto_componente.label }}</label>
                        {{ form.producto_componente }}
                    </td>
                    <td>
                        <label>{{ form.cantidad.label }}</label>
                        {{ form.cantidad }}
                    </td>
                    <td>
                        <span>{{ form.instance.producto_componente.precio_compra|floatformat:2 }}</span>
                    </td>
                    <td>
                        <span>{{ form.instance.cantidad|default:"0"|multiply:form.instance.producto_componente.precio_compra|floatformat:2 }}</span>
                    </td>
                    <td>
                        <label for="{{ form.DELETE.id_for_label }}">Eliminar</label>
                        {{ form.DELETE }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="form-group">
        <strong>Costo Total de Producción: {{ costo_total_produccion|floatformat:2 }}</strong>
    </div>
    <button type="submit" class="btn btn-primary">Guardar cambios</button>
</form>

<a href="{% url 'Producto:listar_productos_fabricacion' %}" class="btn btn-link">Volver a la lista</a>

{% endblock %}

Producto/templates/Producto/editar_producto.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Editar Producto: {{ producto.nombre }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
</div>
{% endblock %}

Producto/templates/Producto/eliminar_producto.html
{% extends 'base.html' %}

{% block title %}Eliminar Producto{% endblock %}

{% block content %}
  <h1>¿Estás seguro de que deseas eliminar al producto {{ producto.nombre }}?</h1>

  <form method="post">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
    <a href="{% url 'Producto:listar_productos' %}">Cancelar</a>
  </form>
{% endblock %}

Producto/templates/Producto/lista_productos_prod.html
{% extends "base.html" %}

{% block content %}
<h1>Productos para Fabricación</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Código</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Precio Compra</th>
            <th>Precio Venta</th>
            <th>Stock</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for producto in productos %}
        <tr>
            <td>{{ producto.codigo }}</td>
            <td>{{ producto.nombre }}</td>
            <td>{{ producto.descripcion }}</td>
            <td>{{ producto.precio_compra }}</td>
            <td>{{ producto.precio_venta }}</td>
            <td>{{ producto.stock }}</td>
            <td>
                <a href="{% url 'Producto:aumentar_stock' producto.id %}" class="btn btn-secondary">Aumentar</a>
                <a href="{% url 'Producto:ver_detalle_producto' producto.id %}" class="btn btn-info">Ver Detalle</a>
                <a href="{% url 'Producto:editar_componentes_producto' producto.id %}" class="btn btn-primary">Editar Componentes</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

Producto/templates/Producto/listar_productos.html
{% extends "base.html" %}

{% block content %}
<h1>Lista de Productos</h1>

<a href="{% url 'Producto:agregar_producto' %}" class="btn btn-success">Crear Producto</a>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Código</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Precio Compra</th>
            <th>Precio Venta</th>
            <th>Stock</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for producto in productos %}
        <tr>
            <td>{{ producto.codigo }}</td>
            <td>{{ producto.nombre }}</td>
            <td>{{ producto.descripcion }}</td>
            <td>{{ producto.precio_compra }}</td>
            <td>{{ producto.precio_venta }}</td>
            <td>{{ producto.stock }}</td>
            <td>
                <a href="{% url 'Producto:editar_producto' producto.id %}" class="btn btn-primary">Editar</a>
                <a href="{% url 'Producto:eliminar_producto' producto.id %}" class="btn btn-danger">Eliminar</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

Producto/templates/Producto/materia_prima.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <table id="tablaMateriaPrima">
        <thead>
            <tr>
                <th>Cantidad</th>
                <th>Nombre</th>
                <th>Precio Unitario</th>
                <th>Costo Total</th>
            </tr>
        </thead>
        <tbody>
            <!-- Las filas se agregarán dinámicamente aquí -->
        </tbody>
    </table>
    <button type="button" id="btnBuscarProducto">Buscar Producto</button>
    <input type="text" id="costoTotalProduccion" readonly>
</form>

<script src="path_to_your_script.js"></script>  <!-- Asegúrate de que la ruta a tu script JavaScript sea correcta -->
{% endblock %}

Producto/templates/Producto/ver_detalle_producto.html
{% extends "base.html" %}

{% block content %}
<h1>Detalle del Producto: {{ producto.nombre }}</h1>

<h2>Componentes</h2>
<table class="table">
    <thead>
        <tr>
            <th>Nombre de Materia Prima</th>
            <th>Cantidad Necesaria</th>
            <th>Stock Actual</th>
        </tr>
    </thead>
    <tbody>
        {% for componente in componentes %}
        <tr>
            <td>{{ componente.nombre }}</td>
            <td>{{ componente.cantidad_necesaria }}</td>
            <td>{{ componente.stock_actual }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3">Este producto no tiene componentes.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a href="{% url 'Producto:listar_productos_fabricacion' %}">Volver a la lista de productos</a>

{% endblock %}