Aplicacion/urls.py
from django.urls import path
from . import views

app_name = 'Aplicacion'

urlpatterns = [
    
    path("", views.home, name="home"),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
]

Producto/urls.py
from django.urls import path
from . import views

app_name = 'Producto'

urlpatterns = [
    path('listar_productos/', views.listar_productos, name='listar_productos'),
    path('agregar_producto/', views.agregar_producto, name='agregar_producto'),
    path('producto/editar/<int:producto_id>/', views.editar_producto, name='editar_producto'),
    path('producto/eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    #path('agregar_componentes/<int:producto_id>/', views.agregar_componentes, name='agregar_componentes'),
    path('get_productos/', views.get_productos, name='get_productos'),
    path('productos_fabricacion/', views.listar_productos_fabricacion, name='listar_productos_fabricacion'),
    path('producto/<int:producto_id>/aumentar/', views.aumentar_stock, name='aumentar_stock'),
    path('producto/<int:producto_id>/detalle/', views.ver_detalle_producto, name='ver_detalle_producto'),
    #path('productos/seleccionar_principal/', views.seleccionar_producto_principal, name='seleccionar_producto_principal'),
    #path('producto/<int:producto_id>/agregar_componentes/', views.agregar_componentes, name='agregar_componentes'),
    path('producto/<int:producto_id>/editar-componentes/', views.editar_componentes_producto, name='editar_componentes_producto'),
    # Añadir más URLs aquí
]

Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Aplicacion.urls', namespace='Aplicacion')),
    path('', include('Usuarios.urls', namespace='Usuarios')),
    path('', include('Producto.urls', namespace='Producto')),
    path('admin/', admin.site.urls),
]

Usuarios/urls.py
from django.urls import path
from . import views

app_name = 'Usuarios'

urlpatterns = [
path('users/', views.list_users, name='list_users'),
path('users/create/', views.create_user, name='create_user'),
path('users/edit/<int:user_id>/', views.edit_user, name='edit_user'),
path('users/delete/<int:user_id>/', views.delete_user, name='delete_user'),
]

Aplicacion/models.py
from django.db import models

# Create your models here.

Aplicacion/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

Aplicacion/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import UserLoginForm, UserRegisterForm

def home(request):
    return render(request, 'home.html')

def login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password'])
            if user:
                login(request, user)
                return redirect('Aplicacion:home')
    else:
        form = UserLoginForm()
    return render(request, 'login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('Aplicacion:login')

def register_view(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Aplicacion:login')
    else:
        form = UserRegisterForm()
    return render(request, 'register.html', {'form': form})

Aplicacion/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mi Aplicación Django{% endblock %}</title>
    <!-- Vincular tus hojas de estilo aquí, por ejemplo: -->
    <!--link rel="stylesheet" href="{% static 'Aplicacion/css/styles.css' %}"-->


    <style>
        /* Estilo para el contenedor del menú desplegable */
        .dropdown {
            position: relative;
            display: inline-block;
        }

        /* Estilo para el contenido desplegable (por defecto oculto) */
        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
            z-index: 1;
        }

        /* Estilo para los ítems del menú desplegable */
        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

        /* Muestra el menú desplegable al pasar el mouse sobre el contenedor */
        .dropdown:hover .dropdown-content {
            display: block;
        }

        /* Cambia el color de fondo al pasar el mouse sobre los ítems del menú desplegable */
        .dropdown-content a:hover {
            background-color: #ddd;
        }
    </style>

</head>

<body>
    <header>
        <nav>
            <!-- Puedes agregar una barra de navegación aquí, por ejemplo: -->
            {% if user.is_authenticated %}
            <a href="{% url 'Aplicacion:home' %}">Inicio</a>
            <a href="{% url 'Usuarios:list_users' %}">Usuarios</a>
            <div class="dropdown">
                <a href="#">Productos</a>
                <div class="dropdown-content">
                    <a href="{% url 'Producto:listar_productos' %}">Productos</a>
                    <a href="{% url 'Producto:listar_productos_fabricacion' %}">Fabricacion</a>
                </div>
            </div>
            <a href="{% url 'Aplicacion:logout' %}">Proveedores</a>
            <a href="{% url 'Aplicacion:logout' %}">Clientes</a>
            <a href="{% url 'Aplicacion:logout' %}">Ventas</a>
            <a href="{% url 'Aplicacion:logout' %}">Compras</a>
            <a href="{% url 'Aplicacion:logout' %}">Reportes</a>
            <a href="{% url 'Aplicacion:logout' %}">Cerrar sesión</a>
            {% else %}
            <a href="{% url 'Aplicacion:login' %}">Iniciar sesión</a>
            <a href="{% url 'Aplicacion:register' %}">Registrarse</a>
            {% endif %}
        </nav>
    </header>

    <main>
        {% block content %}
        <!-- El contenido específico de cada página se insertará aquí -->
        {% endblock %}
    </main>

    <footer>
        <!-- Puedes agregar un pie de página aquí, por ejemplo: -->
        <p>&copy; 2023 Mi Aplicación Django</p>
    </footer>

    <!-- Vincular tus scripts de JavaScript aquí, por ejemplo: -->
    <!-- <script src="{% static 'js/scripts.js' %}"></script> -->
    <!-- CSS de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- JavaScript de Bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>

</html>

Aplicacion/templates/home.html
{% extends 'base.html' %}

{% block title %}Página de Inicio{% endblock %}

{% block content %}
  <h1>Bienvenido, {{ user.username }}!</h1>
  <p>Gracias por iniciar sesión en nuestra aplicación.</p>

  <!-- Puedes agregar más contenido específico para la página de inicio aquí -->
{% endblock %}

Aplicacion/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

Aplicacion/templates/register.html
{% extends 'base.html' %}

{% block content %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}